export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'de', name: 'Deutsch' },
  { code: 'es', name: 'Español' },
  { code: 'pt', name: 'Português' },
  { code: 'fr', name: 'Français' },
  { code: 'it', name: 'Italiano' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'ar', name: 'العربية' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' },
  { code: 'zh', name: '中文' },
];

export const UI_LABELS: Record<string, any> = {
  en: {
    language: "Content Language",
    businessType: "Business Type / Preset",
    businessName: "Business Name",
    serviceCategory: "Service Category",
    streetAddress: "Street Address",
    city: "City",
    district: "District / Area",
    stateRegion: "State / Region",
    postalCode: "Postal Code",
    country: "Country",
    countryCode: "Country Code (ISO)",
    websiteUrl: "Website URL",
    businessNamePlaceholder: "e.g. Acme Plumb",
    serviceCategoryPlaceholder: "e.g. Emergency P",
    streetPlaceholder: "e.g. 123 Business Way",
    cityPlaceholder: "e.g. Hamburg",
    districtPlaceholder: "e.g. Altona",
    statePlaceholder: "e.g. Hamburg",
    postalPlaceholder: "e.g. 21107",
    countryPlaceholder: "e.g. Germany",
    countryCodePlaceholder: "E.G. DE",
    websitePlaceholder: "e.g. https://example.com",
    addressNote: "Note: This information is applied globally to all images. Use the individual editor for per-image captions and titles.",
    aiSeoTitle: "AI SEO & Schema Info",
    schemaLabel: "JSON-LD Schema Markup",
    ogLabel: "OpenGraph & Social Meta",
    semanticLabel: "Semantic Keywords Clusters",
    copySchema: "Copy Schema",
    copyOg: "Copy OG Tags",
    imageTitle: "Image Title",
    serviceDescription: "Service / Description",
    keywordsTags: "Keywords / Tags",
    altText: "Alt Text",
    priorityNote: "PRIORITY: This meta will override global settings.",
    fileName: "File Name",
    aiSuggest: "AI SUGGEST",
    imageTitlePlaceholder: "e.g. Roof Repair Service",
    serviceDescriptionPlaceholder: "e.g. Professional roof repair and maintenance...",
    keywordsPlaceholder: "roofing, repair, local",
    altTextPlaceholder: "Image description for accessibility",
    faqTitle: "Frequently Asked Questions",
    faqSubtitle: "Detailed localized answers for your business",
    extractFromUrl: "Extract Photos from URL",
    pasteUrlPlaceholder: "Paste a webpage URL to extract images...",
    extractButton: "Extract Photos",
    extractNote: "Works best with public webpages and direct image URLs"
  },
  de: {
    language: "Inhaltssprache",
    businessType: "Geschäftstyp / Voreinstellung",
    businessName: "Unternehmensname",
    serviceCategory: "Dienstleistungskategorie",
    streetAddress: "Straße & Hausnummer",
    city: "Stadt",
    district: "Bezirk / Stadtteil",
    stateRegion: "Bundesland / Region",
    postalCode: "Postleitzahl",
    country: "Land",
    countryCode: "Ländercode (ISO)",
    websiteUrl: "Website-URL",
    businessNamePlaceholder: "z.B. Schmidt Sanitär",
    serviceCategoryPlaceholder: "z.B. Notfall-Klempner",
    streetPlaceholder: "z.B. Hauptstraße 1",
    cityPlaceholder: "z.B. Berlin",
    districtPlaceholder: "z.B. Mitte",
    statePlaceholder: "z.B. Berlin",
    postalPlaceholder: "z.B. 10115",
    countryPlaceholder: "z.B. Deutschland",
    countryCodePlaceholder: "Z.B. DE",
    websitePlaceholder: "z.B. https://example.de",
    addressNote: "Hinweis: Diese Informationen werden global auf alle Bilder angewendet. Verwenden Sie den individuellen Editor für bildspezifische Titel.",
    aiSeoTitle: "KI-SEO & Schema-Info",
    schemaLabel: "JSON-LD Schema-Markup",
    ogLabel: "OpenGraph & Social Meta",
    semanticLabel: "Semantische Keyword-Cluster",
    copySchema: "Schema kopieren",
    copyOg: "OG-Tags kopieren",
    imageTitle: "Bildtitel",
    serviceDescription: "Dienstleistung / Beschreibung",
    keywordsTags: "Schlüsselwörter / Tags",
    altText: "Alt-Text",
    priorityNote: "PRIORITÄT: Diese Meta-Daten überschreiben globale Einstellungen.",
    fileName: "Dateiname",
    aiSuggest: "KI-Vorschlag",
    imageTitlePlaceholder: "z.B. Dachreparatur-Service",
    serviceDescriptionPlaceholder: "z.B. Professionelle Dachreparatur und Wartung...",
    keywordsPlaceholder: "Dachdeckung, Reparatur, lokal",
    altTextPlaceholder: "Bildbeschreibung für Barrierefreiheit",
    faqTitle: "Häufig gestellte Fragen (FAQ)",
    faqSubtitle: "Detaillierte lokalisierte Antworten für Ihr Unternehmen",
    extractFromUrl: "Fotos aus URL extrahieren",
    pasteUrlPlaceholder: "Webseiten-URL einfügen...",
    extractButton: "Fotos extrahieren",
    extractNote: "Funktioniert am besten mit öffentlichen Webseiten"
  },
  fr: {
    language: "Langue du contenu",
    businessType: "Type d'entreprise / Préréglage",
    businessName: "Nom de l'entreprise",
    serviceCategory: "Catégorie de service",
    streetAddress: "Adresse",
    city: "Ville",
    district: "Quartier / Zone",
    stateRegion: "Région / État",
    postalCode: "Code postal",
    country: "Pays",
    countryCode: "Code pays (ISO)",
    websiteUrl: "URL du site web",
    businessNamePlaceholder: "ex. Plomberie Martin",
    serviceCategoryPlaceholder: "ex. Plombier d'urgence",
    streetPlaceholder: "ex. 10 rue de la Paix",
    cityPlaceholder: "ex. Paris",
    districtPlaceholder: "ex. Le Marais",
    statePlaceholder: "ex. Île-de-France",
    postalPlaceholder: "ex. 75001",
    countryPlaceholder: "ex. France",
    countryCodePlaceholder: "EX. FR",
    websitePlaceholder: "ex. https://exemple.fr",
    addressNote: "Remarque : ces informations sont appliquées globalement à toutes les images. Utilisez l'éditeur individuel pour les légendes par image.",
    aiSeoTitle: "Infos SEO IA & Schema",
    schemaLabel: "Balisage Schema JSON-LD",
    ogLabel: "OpenGraph & Social Meta",
    semanticLabel: "Clusters de mots-clés sémantiques",
    copySchema: "Copier le schéma",
    copyOg: "Copier les tags OG",
    imageTitle: "Titre de l'image",
    serviceDescription: "Service / Description",
    keywordsTags: "Mots-clés / Tags",
    altText: "Texte alternatif",
    priorityNote: "PRIORITÉ : Ces métadonnées remplaceront les paramètres globaux.",
    fileName: "Nom du fichier",
    aiSuggest: "SUGGESTION IA",
    imageTitlePlaceholder: "ex. Service de réparation de toiture",
    serviceDescriptionPlaceholder: "ex. Réparation et entretien de toiture professionnels...",
    keywordsPlaceholder: "toiture, réparation, local",
    altTextPlaceholder: "Description de l'image pour l'accessibilité",
    faqTitle: "Questions Fréquemment Posées (FAQ)",
    faqSubtitle: "Réponses localisées détaillées pour votre entreprise",
    extractFromUrl: "Extraire des photos d'une URL",
    pasteUrlPlaceholder: "Collez l'URL d'une page web...",
    extractButton: "Extraire les photos",
    extractNote: "Idéal pour les pages web publiques"
  },
  es: {
    language: "Idioma del contenido",
    businessType: "Tipo de negocio / Preajuste",
    businessName: "Nombre del negocio",
    serviceCategory: "Categoría de servicio",
    streetAddress: "Dirección",
    city: "Ciudad",
    district: "Distrito / Área",
    stateRegion: "Región / Estado",
    postalCode: "Código postal",
    country: "País",
    countryCode: "Código de país (ISO)",
    websiteUrl: "URL del sitio web",
    businessNamePlaceholder: "ej. Fontanería Pérez",
    serviceCategoryPlaceholder: "ej. Fontanero de urgencia",
    streetPlaceholder: "ej. Calle Mayor 1",
    cityPlaceholder: "ej. Madrid",
    districtPlaceholder: "ej. Retiro",
    statePlaceholder: "ej. Madrid",
    postalPlaceholder: "ej. 28001",
    countryPlaceholder: "ej. España",
    countryCodePlaceholder: "EJ. ES",
    websitePlaceholder: "ej. https://ejemplo.es",
    addressNote: "Nota: Esta información se aplica globalmente a todas las imágenes. Use el editor individual para subtítulos por imagen.",
    aiSeoTitle: "Información SEO y Schema de IA",
    schemaLabel: "Marcado de Schema JSON-LD",
    ogLabel: "OpenGraph y Social Meta",
    semanticLabel: "Clusters de palabras clave semánticas",
    copySchema: "Copiar esquema",
    copyOg: "Copiar etiquetas OG",
    imageTitle: "Título de la imagen",
    serviceDescription: "Servicio / Descripción",
    keywordsTags: "Palabras clave / Etiquetas",
    altText: "Texto alternativo",
    priorityNote: "PRIORIDAD: Estos metadatos anularán la configuración global.",
    fileName: "Nombre del archivo",
    aiSuggest: "SUGERENCIA IA",
    imageTitlePlaceholder: "ej. Servicio de reparación de techos",
    serviceDescriptionPlaceholder: "ej. Reparación y mantenimiento profesional de techos...",
    keywordsPlaceholder: "techado, reparación, local",
    altTextPlaceholder: "Descripción de la imagen para accesibilidad",
    faqTitle: "Preguntas Frecuentes (FAQ)",
    faqSubtitle: "Respuestas localizadas detalladas para su negocio",
    extractFromUrl: "Extraer fotos de URL",
    pasteUrlPlaceholder: "Pegue la URL de una página web...",
    extractButton: "Extraer fotos",
    extractNote: "Mejor con páginas web públicas"
  },
  it: {
    language: "Lingua del contenuto",
    businessType: "Tipo di attività / Predefinito",
    businessName: "Nome dell'attività",
    serviceCategory: "Categoria di servizio",
    streetAddress: "Indirizzo",
    city: "Città",
    district: "Quartiere / Area",
    stateRegion: "Regione / Stato",
    postalCode: "Codice postale",
    country: "Paese",
    countryCode: "Codice paese (ISO)",
    websiteUrl: "URL del sito web",
    businessNamePlaceholder: "es. Idraulica Rossi",
    serviceCategoryPlaceholder: "es. Idraulico di urgenza",
    streetPlaceholder: "es. Via Roma 1",
    cityPlaceholder: "es. Milano",
    districtPlaceholder: "es. Navigli",
    statePlaceholder: "es. Lombardia",
    postalPlaceholder: "es. 20100",
    countryPlaceholder: "es. Italia",
    countryCodePlaceholder: "ES. IT",
    websitePlaceholder: "es. https://esempio.it",
    addressNote: "Nota: queste informazioni vengono applicate globalmente a tutte le immagini. Utilizzare l'editor individuale per i titoli per immagine.",
    aiSeoTitle: "Info SEO IA & Schema",
    schemaLabel: "Markup Schema JSON-LD",
    ogLabel: "OpenGraph & Social Meta",
    semanticLabel: "Cluster di parole chiave semantiche",
    copySchema: "Copia schema",
    copyOg: "Copia tag OG",
    imageTitle: "Titolo dell'immagine",
    serviceDescription: "Servizio / Descrizione",
    keywordsTags: "Parole chiave / Tag",
    altText: "Testo alternativo",
    priorityNote: "PRIORITÀ: Questi metadati sovrascriveranno le impostazioni globali.",
    fileName: "Nome del file",
    aiSuggest: "SUGGERIMENTO IA",
    imageTitlePlaceholder: "es. Servizio di riparazione tetti",
    serviceDescriptionPlaceholder: "es. Riparazione e manutenzione professionale dei tetti...",
    keywordsPlaceholder: "copertura, riparazione, locale",
    altTextPlaceholder: "Descrizione dell'immagine per l'accessibilità",
    faqTitle: "Domande Frequenti (FAQ)",
    faqSubtitle: "Risposte localizzate dettagliate per la tua attività",
    extractFromUrl: "Estrai foto da URL",
    pasteUrlPlaceholder: "Incolla l'URL di una pagina web...",
    extractButton: "Estrai foto",
    extractNote: "Funziona meglio con pagine web pubbliche"
  },
  pt: {
    language: "Idioma do conteúdo",
    businessType: "Tipo de negócio / Predefinição",
    businessName: "Nome do negócio",
    serviceCategory: "Categoria de serviço",
    streetAddress: "Endereço",
    city: "Cidade",
    district: "Bairro / Área",
    stateRegion: "Estado / Região",
    postalCode: "Código postal",
    country: "País",
    countryCode: "Código do país (ISO)",
    websiteUrl: "URL do site",
    businessNamePlaceholder: "ex. Canalizações Silva",
    serviceCategoryPlaceholder: "ex. Canalizador de urgência",
    streetPlaceholder: "ex. Rua Direita 1",
    cityPlaceholder: "ex. Lisboa",
    districtPlaceholder: "ex. Alfama",
    statePlaceholder: "ex. Lisboa",
    postalPlaceholder: "ex. 1000-001",
    countryPlaceholder: "ex. Portugal",
    countryCodePlaceholder: "EX. PT",
    websitePlaceholder: "ex. https://exemplo.pt",
    addressNote: "Nota: Estas informações são aplicadas globalmente a todas as imagens. Utilize o editor individual para legendas por imagem.",
    aiSeoTitle: "Informações de SEO e Esquema de IA",
    schemaLabel: "Marcação de Esquema JSON-LD",
    ogLabel: "OpenGraph e Social Meta",
    semanticLabel: "Clusters de palavras-chave semânticas",
    copySchema: "Copiar esquema",
    copyOg: "Copiar tags OG",
    imageTitle: "Título da imagem",
    serviceDescription: "Serviço / Descrição",
    keywordsTags: "Palavras-chave / Tags",
    altText: "Texto alternativo",
    priorityNote: "PRIORIDADE: Estes metadados substituirão as configurações globais.",
    fileName: "Nome do arquivo",
    aiSuggest: "SUGESTÃO IA",
    imageTitlePlaceholder: "ex. Serviço de reparação de telhados",
    serviceDescriptionPlaceholder: "ex. Reparação e manutencão profissional de telhados...",
    keywordsPlaceholder: "telhado, riparação, local",
    altTextPlaceholder: "Descrição da imagem para acessibilidade",
    faqTitle: "Perguntas Frequentes (FAQ)",
    faqSubtitle: "Respostas localizadas detalhadas para o seu negócio",
    extractFromUrl: "Extrair fotos de URL",
    pasteUrlPlaceholder: "Cole o URL de uma página web...",
    extractButton: "Extrair fotos",
    extractNote: "Funciona melhor con páginas web públicas"
  },
  tr: {
    language: "İçerik Dili",
    businessType: "İşletme Türü / Hazır Ayar",
    businessName: "İşletme Adı",
    serviceCategory: "Hizmet Kategorisi",
    streetAddress: "Sokak Adresi",
    city: "Şehir",
    district: "İlçe / Semt",
    stateRegion: "Eyalet / Bölge",
    postalCode: "Posta Kodu",
    country: "Ülke",
    countryCode: "Ülke Kodu (ISO)",
    websiteUrl: "Web Sitesi URL'si",
    businessNamePlaceholder: "örn. Ahmet Tesisat",
    serviceCategoryPlaceholder: "örn. Acil Tesisatçı",
    streetPlaceholder: "örn. Atatürk Cad. No:1",
    cityPlaceholder: "örn. İstanbul",
    districtPlaceholder: "örn. Beşiktaş",
    statePlaceholder: "örn. İstanbul",
    postalPlaceholder: "örn. 34330",
    countryPlaceholder: "örn. Türkiye",
    countryCodePlaceholder: "ÖRN. TR",
    websitePlaceholder: "örn. https://ornek.com.tr",
    addressNote: "Not: Bu bilgiler tüm resimlere genel olarak uygulanır. Resme özel başlıklar için bireysel düzenleyiciyi kullanın.",
    aiSeoTitle: "Yapay Zeka SEO ve Şema Bilgisi",
    schemaLabel: "JSON-LD Şema İşareti",
    ogLabel: "OpenGraph ve Sosyal Meta",
    semanticLabel: "Semantik Anahtar Kelime Kümeleri",
    copySchema: "Şemayı Kopyala",
    copyOg: "OG Etiketlerini Kopyala",
    imageTitle: "Resim Başlığı",
    serviceDescription: "Hizmet / Açıklama",
    keywordsTags: "Anahtar Kelimeler / Etiketler",
    altText: "Alt Metin",
    priorityNote: "ÖNCELİK: Bu meta veriler genel ayarları geçersiz kılacaktır.",
    fileName: "Dosya Adı",
    aiSuggest: "Yapay Zeka Önerisi",
    imageTitlePlaceholder: "örn. Çatı Tamir Hizmeti",
    serviceDescriptionPlaceholder: "örn. Profesyonel çatı tamiri ve bakımı...",
    keywordsPlaceholder: "çatı, tamir, yerel",
    altTextPlaceholder: "Erişilebilirlik için resim açıklaması",
    faqTitle: "Sıkça Sorulan Sorular (SSS)",
    faqSubtitle: "İşletmeniz için ayrıntılı yerelleştirilmiş yanıtlar",
    extractFromUrl: "URL'den Fotoğraf Çıkar",
    pasteUrlPlaceholder: "Bir web sayfası URL'si yapıştırın...",
    extractButton: "Fotoğrafları Çıkar",
    extractNote: "Halka açık web sayfalarıyla en iyi şekilde çalışır"
  },
  ar: {
    language: "لغة المحتوى",
    businessType: "نوع العمل / الإعداد المسبق",
    businessName: "اسم العمل",
    serviceCategory: "فئة الخدمة",
    streetAddress: "عنوان الشارع",
    city: "المدينة",
    district: "الحي / المنطقة",
    stateRegion: "الولاية / المنطقة",
    postalCode: "الرمز البريدي",
    country: "البلد",
    countryCode: "رمز البلد (ISO)",
    websiteUrl: "رابط الموقع",
    businessNamePlaceholder: "مثال: سباكة الأمانة",
    serviceCategoryPlaceholder: "مثال: سباك طوارئ",
    streetPlaceholder: "مثال: 123 شارع الأعمال",
    cityPlaceholder: "مثال: دبي",
    districtPlaceholder: "مثال: ديرة",
    statePlaceholder: "مثال: دبي",
    postalPlaceholder: "مثال: 00000",
    countryPlaceholder: "مثال: الإمارات العربية المتحدة",
    countryCodePlaceholder: "مثال: AE",
    websitePlaceholder: "مثال: https://example.ae",
    addressNote: "ملاحظة: يتم تطبيق هذه المعلومات بشكل عام على جميع الصور. استخدم المحرر الفردي لكل صورة.",
    aiSeoTitle: "معلومات SEO ومخطط الذكاء الاصطناعي",
    schemaLabel: "ترميز مخطط JSON-LD",
    ogLabel: "OpenGraph وميتا الاجتماعية",
    semanticLabel: "عناقيد الكلمات الدلالية",
    copySchema: "نسخ المخطط",
    copyOg: "نسخ علامات OG",
    imageTitle: "عنوان الصورة",
    serviceDescription: "الخدمة / الوصف",
    keywordsTags: "الكلمات الدالة / العلامات",
    altText: "النص البديل",
    priorityNote: "أولوية: ستتجاوز هذه البيانات الإعدادات العامة.",
    fileName: "اسم الملف",
    aiSuggest: "اقتراح الذكاء الاصطناعي",
    imageTitlePlaceholder: "مثال: خدمة إصلاح الأسطح",
    serviceDescriptionPlaceholder: "مثال: إصلاح وصيانة الأسطح المهنية...",
    keywordsPlaceholder: "تسقيف، إصلاح، محلي",
    altTextPlaceholder: "وصف الصورة لإمكانية الوصول",
    faqTitle: "الأسئلة الشائعة",
    faqSubtitle: "إجابات محلية مفصلة لعملك",
    extractFromUrl: "استخراج الصور من الرابط",
    pasteUrlPlaceholder: "أدخل رابط موقع إلكتروني...",
    extractButton: "استخراج الصور",
    extractNote: "يعمل بشكل أفضل مع صفحات الويب العامة"
  },
  hi: {
    language: "कंटेंट भाषा",
    businessType: "व्यवसाय प्रकार / प्रीसेट",
    businessName: "व्यवसाय का नाम",
    serviceCategory: "सेवा श्रेणी",
    streetAddress: "सड़क का पता",
    city: "शहर",
    district: "ज़िला / क्षेत्र",
    stateRegion: "राज्य / क्षेत्र",
    postalCode: "पिन कोड",
    country: "देश",
    countryCode: "देश कोड (ISO)",
    websiteUrl: "वेबसाइट URL",
    businessNamePlaceholder: "जैसे: शर्मा प्लंबिंग",
    serviceCategoryPlaceholder: "जैसे: इमरजेंसी प्लंबर",
    streetPlaceholder: "जैसे: 123 बिजनेस वे",
    cityPlaceholder: "जैसे: दिल्ली",
    districtPlaceholder: "जैसे: चांदनी चौक",
    statePlaceholder: "जैसे: दिल्ली",
    postalPlaceholder: "जैसे: 110001",
    countryPlaceholder: "जैसे: भारत",
    countryCodePlaceholder: "जैसे: IN",
    websitePlaceholder: "जैसे: https://example.in",
    addressNote: "नोट: यह जानकारी वैश्विक स्तर पर सभी छवियों पर लागू होती है। प्रति-छवि कैप्शन के लिए व्यक्तिगत संपादक का उपयोग करें।",
    aiSeoTitle: "AI SEO और स्कीमा जानकारी",
    schemaLabel: "JSON-LD स्कीमा मार्कアップ",
    ogLabel: "OpenGraph और सोशल मेटा",
    semanticLabel: "सिमेंटिक कीवर्ड क्लस्टर",
    copySchema: "स्कीमा कॉपी करें",
    copyOg: "OG टैग कॉपी करें",
    imageTitle: "छवि शीर्षक",
    serviceDescription: "सेवा / विवरण",
    keywordsTags: "कीवर्ड / टैग",
    altText: "ऑल्ट टेक्स्ट",
    priorityNote: "प्राथमिकता: यह मेटा वैश्विक सेटिंग्स को ओवरライド करेगा।",
    fileName: "फ़ाइल का नाम",
    aiSuggest: "AI सुझाव",
    imageTitlePlaceholder: "जैसे: छत मरम्मत सेवा",
    serviceDescriptionPlaceholder: "जैसे: पेशेवर छत मरम्मत और रखरखाव...",
    keywordsPlaceholder: "छत, मरम्मत, स्थानीय",
    altTextPlaceholder: "सुगम्यता के लिए छवि विवरण",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
    faqSubtitle: "आपके व्यवसाय के लिए विस्तृत स्थानीयकृत उत्तर",
    extractFromUrl: "URL से फ़ोटो निकालें",
    pasteUrlPlaceholder: "वेबपेज URL पेस्ट करें...",
    extractButton: "फ़ोटो निकालें",
    extractNote: "सार्वजनिक वेबपेजों के साथ सबसे अच्छा काम करता है"
  },
  ja: {
    language: "コンテンツ言語",
    businessType: "業種 / プリセット",
    businessName: "屋号・会社名",
    serviceCategory: "サービスカテゴリ",
    streetAddress: "住所",
    city: "市区町村",
    district: "地区 / エリア",
    stateRegion: "都道府県",
    postalCode: "郵便番号",
    country: "国",
    countryCode: "国コード (ISO)",
    websiteUrl: "ウェブサイトURL",
    businessNamePlaceholder: "例: 山田水道工業",
    serviceCategoryPlaceholder: "例: 緊急水道修理",
    streetPlaceholder: "例: 中央区銀座1-2-3",
    cityPlaceholder: "例: 東京都",
    districtPlaceholder: "例: 銀座",
    statePlaceholder: "例: 東京都",
    postalPlaceholder: "例: 100-0001",
    countryPlaceholder: "例: 日本",
    countryCodePlaceholder: "例: JP",
    websitePlaceholder: "例: https://example.jp",
    addressNote: "注意：この情報はすべての画像にグローバルに適用されます。画像ごとのキャプションには個別エディタを使用してください。",
    aiSeoTitle: "AI SEO & スキーマ情報",
    schemaLabel: "JSON-LD スキーママークアップ",
    ogLabel: "OpenGraph & ソーシャルメタ",
    semanticLabel: "セマンティックキーワードクラスター",
    copySchema: "スキーマをコピー",
    copyOg: "OGタグをコピー",
    imageTitle: "画像タイトル",
    serviceDescription: "サービス / 説明",
    keywordsTags: "キーワード / タグ",
    altText: "代替テキスト",
    priorityNote: "優先：このメタ情報はグローバル設定を上書きします。",
    fileName: "ファイル名",
    aiSuggest: "AI提案",
    imageTitlePlaceholder: "例：屋根修理サービス",
    serviceDescriptionPlaceholder: "例：プロによる屋根の修理とメンテナンス...",
    keywordsPlaceholder: "屋根, 修理, ローカル",
    altTextPlaceholder: "アクセシビリティのための画像説明",
    faqTitle: "よくある質問 (FAQ)",
    faqSubtitle: "ビジネスに合わせてローカライズされた回答",
    extractFromUrl: "URLから写真を抽出",
    pasteUrlPlaceholder: "ウェブページのURLを貼り付け...",
    extractButton: "写真を抽出",
    extractNote: "公開されているウェブページで最適に動作します"
  },
  zh: {
    language: "内容语言",
    businessType: "业务类型 / 预设",
    businessName: "企业名称",
    serviceCategory: "服务类别",
    streetAddress: "街道地址",
    city: "城市",
    district: "区 / 地区",
    stateRegion: "省份 / 自治区",
    postalCode: "邮政编码",
    country: "国家",
    countryCode: "国家代码 (ISO)",
    websiteUrl: "网站网址",
    businessNamePlaceholder: "例如：阿克梅管道",
    serviceCategoryPlaceholder: "例如：紧急管道工",
    streetPlaceholder: "例如：商务路123号",
    cityPlaceholder: "例如：上海",
    districtPlaceholder: "例如：黄浦区",
    statePlaceholder: "例如：上海市",
    postalPlaceholder: "例如：200001",
    countryPlaceholder: "例如：中国",
    countryCodePlaceholder: "例如：CN",
    websitePlaceholder: "例如：https://example.cn",
    addressNote: "注意：此信息全局应用于所有图像。对于每张图像的标题，请使用个人编辑器。",
    aiSeoTitle: "AI SEO 和架构信息",
    schemaLabel: "JSON-LD 架构标记",
    ogLabel: "OpenGraph 和社交元数据",
    semanticLabel: "语义关键词集群",
    copySchema: "复制架构",
    copyOg: "复制 OG 标签",
    imageTitle: "图片标题",
    serviceDescription: "服务 / 描述",
    keywordsTags: "关键词 / 标签",
    altText: "替代文本",
    priorityNote: "优先级：此元数据将覆盖全局设置。",
    fileName: "文件名",
    aiSuggest: "AI 建议",
    imageTitlePlaceholder: "例如：屋顶维修服务",
    serviceDescriptionPlaceholder: "例如：专业的屋顶维修和维护...",
    keywordsPlaceholder: "屋顶, 维修, 本地",
    altTextPlaceholder: "为了无障碍性的图片说明",
    faqTitle: "常见问题解答 (FAQ)",
    faqSubtitle: "针对您业务的详细本地化解答",
    extractFromUrl: "从 URL 提取照片",
    pasteUrlPlaceholder: "粘贴网页 URL...",
    extractButton: "提取照片",
    extractNote: "最适合公开网页"
  }
};
