export const toolDict: Record<string, any> = {
  en: {
    dropTitle: 'Drop JPG or JPEG images here',
    dropSub: 'or click to select files',
    batchApply: 'Apply Settings to All Images',
    clearAll: 'Clear All',
    searchPlaceholder: 'Search city, state, address, landmark...',
    lat: 'Latitude',
    lng: 'Longitude',
    invalidCoords: 'Enter valid decimal coordinates',
    writeTags: 'Write Metadata & Download',
    downloading: 'Processing...',
    successFiles: 'files processed successfully!',
    errorNoLoc: 'Please pin a location on the map before applying the geotag.',
    errorGeneral: 'An error occurred. Please try again.',
    metadataHeader: 'Local SEO Metadata (Optional)',
    title: 'Title',
    desc: 'Description',
    keywords: 'Keywords (comma separated)',
    business: 'Business Name',
    city: 'City',
    district: 'District',
    country: 'Country',
    gpsTab: 'GPS Location',
    metaTab: 'Metadata',
    preview: 'Image Metadata',
    gpsFound: 'Status: Found',
    gpsNotFound: 'Status: Not found',
    noGpsMsg: 'No GPS coordinates were found in this image.',
    imgDetails: 'Image Details',
    cameraInfo: 'Camera Info',
    format: 'Format',
    dimensions: 'Dimensions',
    make: 'Camera Make',
    model: 'Camera Model',
    date: 'Date Taken',
    writeSingle: 'Update EXIF & Download',
    editImage: 'Edit',
    processing: 'Processing...',
  },
  tr: {
    dropTitle: 'JPG veya JPEG resimlerini buraya bırakın',
    dropSub: 'veya dosya seçmek için tıklayın',
    batchApply: 'Tüm Resimlere Uygula',
    clearAll: 'Hepsini Temizle',
    searchPlaceholder: 'Şehir, adres, sembol arayın...',
    lat: 'Enlem',
    lng: 'Boylam',
    invalidCoords: 'Geçerli ondalık koordinatlar girin',
    writeTags: 'Meta Verileri Yaz & İndir',
    downloading: 'İşleniyor...',
    successFiles: 'dosya başarıyla işlendi!',
    errorNoLoc: 'Lütfen etiketlemeden önce haritada bir konum işaretleyin.',
    errorGeneral: 'Bir hata oluştu. Lütfen tekrar deneyin.',
    metadataHeader: 'Yerel SEO Meta Verileri (İsteğe bağlı)',
    title: 'Başlık',
    desc: 'Açıklama',
    keywords: 'Anahtar Kelimeler (virgülle ayırın)',
    business: 'İşletme Adı',
    city: 'Şehir',
    district: 'İlçe',
    country: 'Ülke',
    gpsTab: 'GPS Konumu',
    metaTab: 'Meta Veri',
    preview: 'Resim Meta Verileri',
    gpsFound: 'Durum: Bulundu',
    gpsNotFound: 'Durum: Bulunamadı',
    noGpsMsg: 'Bu resimde GPS koordinatları bulunamadı.',
    imgDetails: 'Resim Detayları',
    cameraInfo: 'Kamera Bilgileri',
    format: 'Format',
    dimensions: 'Boyutlar',
    make: 'Kamera Markası',
    model: 'Kamera Modeli',
    date: 'Çekim Tarihi',
    writeSingle: 'EXIF Güncelle & İndir',
    editImage: 'Düzenle',
    processing: 'İşleniyor...',
  },
  de: {
    dropTitle: 'Ziehen Sie JPG/JPEG-Bilder hierher',
    dropSub: 'oder klicken Sie zur Dateiauswahl',
    batchApply: 'Auf alle Bilder anwenden',
    clearAll: 'Alles löschen',
    searchPlaceholder: 'Stadt, Adresse, Wahrzeichen suchen...',
    lat: 'Breitengrad',
    lng: 'Längengrad',
    invalidCoords: 'Gültige Dezimal-Koordinaten eingeben',
    writeTags: 'Metadaten schreiben & herunterladen',
    downloading: 'Verarbeitung...',
    successFiles: 'Dateien erfolgreich verarbeitet!',
    errorNoLoc: 'Bitte markieren Sie vor dem Tagging einen Ort auf der Karte.',
    errorGeneral: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    metadataHeader: 'Lokale SEO Metadaten (Optional)',
    title: 'Titel',
    desc: 'Beschreibung',
    keywords: 'Schlüsselwörter (kommagetrennt)',
    business: 'Unternehmensname',
    city: 'Stadt',
    district: 'Bezirk',
    country: 'Land',
    gpsTab: 'GPS-Standort',
    metaTab: 'Metadaten',
    preview: 'Bild-Metadaten',
    gpsFound: 'Status: Gefunden',
    gpsNotFound: 'Status: Nicht gefunden',
    noGpsMsg: 'In diesem Bild wurden keine GPS-Koordinaten gefunden.',
    imgDetails: 'Bilddetails',
    cameraInfo: 'Kamerainformationen',
    format: 'Format',
    dimensions: 'Abmessungen',
    make: 'Kameramarke',
    model: 'Kameramodell',
    date: 'Aufnahmedatum',
    writeSingle: 'EXIF aktualisieren & Download',
    editImage: 'Bearbeiten',
    processing: 'Verarbeitung...',
  },
  es: {
    dropTitle: 'Suelta imágenes JPG o JPEG aquí',
    dropSub: 'o haz clic para seleccionar archivos',
    batchApply: 'Aplicar a todas las imágenes',
    clearAll: 'Borrar todo',
    searchPlaceholder: 'Buscar ciudad, dirección, lugar...',
    lat: 'Latitud',
    lng: 'Longitud',
    invalidCoords: 'Introduce coordenadas decimales válidas',
    writeTags: 'Escribir metadatos y descargar',
    downloading: 'Procesando...',
    successFiles: 'archivos procesados con éxito!',
    errorNoLoc: 'Por favor, marca una ubicación en el mapa antes de etiquetar.',
    errorGeneral: 'Se ha producido un error. Por favor, inténtalo de nuevo.',
    metadataHeader: 'Metadatos de SEO local (Opcional)',
    title: 'Título',
    desc: 'Descripción',
    keywords: 'Palabras clave (separadas por comas)',
    business: 'Nombre de la empresa',
    city: 'Ciudad',
    district: 'Distrito',
    country: 'País',
    gpsTab: 'Ubicación GPS',
    metaTab: 'Metadatos',
    preview: 'Metadatos de la imagen',
    gpsFound: 'Estado: Encontrado',
    gpsNotFound: 'Estado: No encontrado',
    noGpsMsg: 'No se encontraron coordenadas GPS en esta imagen.',
    imgDetails: 'Detalles de la imagen',
    cameraInfo: 'Info. de la cámara',
    format: 'Formato',
    dimensions: 'Dimensiones',
    make: 'Marca de cámara',
    model: 'Modelo de cámara',
    date: 'Fecha de captura',
    writeSingle: 'Actualizar EXIF y descargar',
    editImage: 'Editar',
    processing: 'Procesando...',
  },
  pt: {
    dropTitle: 'Solte imagens JPG/JPEG aqui',
    dropSub: 'ou clique para selecionar arquivos',
    batchApply: 'Aplicar a todas as imagens',
    clearAll: 'Limpar tudo',
    searchPlaceholder: 'Pesquisar cidade, endereço...',
    lat: 'Latitude',
    lng: 'Longitude',
    invalidCoords: 'Insira coordenadas decimais válidas',
    writeTags: 'Gravar metadados e baixar',
    downloading: 'Processando...',
    successFiles: 'arquivos processados com sucesso!',
    errorNoLoc: 'Por favor, marque um local no mapa antes de aplicar a tag.',
    errorGeneral: 'Ocorreu um erro. Tente novamente.',
    metadataHeader: 'Metadados de SEO local (Opcional)',
    title: 'Título',
    desc: 'Descrição',
    keywords: 'Palavras-chave (separadas por vírgulas)',
    business: 'Nome do negócio',
    city: 'Cidade',
    district: 'Distrito',
    country: 'País',
    gpsTab: 'Localização GPS',
    metaTab: 'Metadados',
    preview: 'Metadados da imagem',
    gpsFound: 'Status: Encontrado',
    gpsNotFound: 'Status: Não encontrado',
    noGpsMsg: 'Nenhuma coordenada GPS foi encontrada nesta imagem.',
    imgDetails: 'Detalhes da imagem',
    cameraInfo: 'Info. da câmera',
    format: 'Formato',
    dimensions: 'Dimensões',
    make: 'Marca da câmera',
    model: 'Modelo da câmera',
    date: 'Data de captura',
    writeSingle: 'Atualizar EXIF e baixar',
    editImage: 'Editar',
    processing: 'Processando...',
  },
  fr: {
    dropTitle: 'Déposez des images JPG ou JPEG ici',
    dropSub: 'ou cliquez pour sélectionner des fichiers',
    batchApply: 'Appliquer à toutes les images',
    clearAll: 'Tout effacer',
    searchPlaceholder: 'Rechercher ville, adresse, repère...',
    lat: 'Latitude',
    lng: 'Longitude',
    invalidCoords: 'Entrez des coordonnées décimales valides',
    writeTags: 'Enregistrer les métadonnées et télécharger',
    downloading: 'En cours de traitement...',
    successFiles: 'fichiers traités avec succès !',
    errorNoLoc: 'Veuillez épingler un emplacement sur la carte avant de géolocaliser.',
    errorGeneral: 'Une erreur s\'est produite. Veuillez réessayer.',
    metadataHeader: 'Métadonnées SEO Local (Facultatif)',
    title: 'Titre',
    desc: 'Description',
    keywords: 'Mots-clés (séparés par des virgules)',
    business: 'Nom de l\'entreprise',
    city: 'Ville',
    district: 'Quartier',
    country: 'Pays',
    gpsTab: 'Emplacement GPS',
    metaTab: 'Métadonnées',
    preview: 'Métadonnées de l\'image',
    gpsFound: 'Statut : Trouvé',
    gpsNotFound: 'Statut : Non trouvé',
    noGpsMsg: 'Aucune coordonnée GPS trouvée dans cette image.',
    imgDetails: 'Détails de l\'image',
    cameraInfo: 'Infos appareil photo',
    format: 'Format',
    dimensions: 'Dimensions',
    make: 'Marque',
    model: 'Modèle',
    date: 'Date de prise',
    writeSingle: 'Mettre à jour EXIF et télécharger',
    editImage: 'Modifier',
    processing: 'En cours...',
  },
  it: {
    dropTitle: 'Trascina immagini JPG/JPEG qui',
    dropSub: 'o fai clic per selezionare file',
    batchApply: 'Applica a tutte le immagini',
    clearAll: 'Cancella tutto',
    searchPlaceholder: 'Cerca città, indirizzo, luogo...',
    lat: 'Latitudine',
    lng: 'Longitudine',
    invalidCoords: 'Inserisci coordinate decimali valide',
    writeTags: 'Scrivi metadati e scarica',
    downloading: 'Elaborazione in corso...',
    successFiles: 'file elaborati con successo!',
    errorNoLoc: 'Fissa una posizione sulla mappa prima di applicare il geotag.',
    errorGeneral: 'Si è verificato un errore. Riprova.',
    metadataHeader: 'Metadati SEO locale (Facoltativo)',
    title: 'Titolo',
    desc: 'Descrizione',
    keywords: 'Parole chiave (separate da virgole)',
    business: 'Nome dell\'azienda',
    city: 'Città',
    district: 'Quartiere',
    country: 'Paese',
    gpsTab: 'Posizione GPS',
    metaTab: 'Metadati',
    preview: 'Metadati immagine',
    gpsFound: 'Stato: Trovato',
    gpsNotFound: 'Stato: Non trovato',
    noGpsMsg: 'Nessuna coordinata GPS trovata in questa immagine.',
    imgDetails: 'Dettagli immagine',
    cameraInfo: 'Info fotocamera',
    format: 'Formato',
    dimensions: 'Dimensioni',
    make: 'Marca fotocamera',
    model: 'Modello fotocamera',
    date: 'Data di scatto',
    writeSingle: 'Aggiorna EXIF e scarica',
    editImage: 'Modifica',
    processing: 'Elaborazione...',
  },
  nl: {
    dropTitle: 'Sleep JPG/JPEG bestanden hierheen',
    dropSub: 'of klik om bestanden te selecteren',
    batchApply: 'Toepassen op alle afbeeldingen',
    clearAll: 'Alles wissen',
    searchPlaceholder: 'Zoek stad, adres, oriëntatiepunt...',
    lat: 'Breedtegraad',
    lng: 'Lengtegraad',
    invalidCoords: 'Voer geldige decimale coördinaten in',
    writeTags: 'Metadata wegschrijven & Downloaden',
    downloading: 'Verwerken...',
    successFiles: 'bestanden succesvol verwerkt!',
    errorNoLoc: 'Prik een locatie op de kaart voordat je de geotag toepast.',
    errorGeneral: 'Er is een fout opgetreden. Probeer het opnieuw.',
    metadataHeader: 'Lokale SEO Metadata (Optioneel)',
    title: 'Titel',
    desc: 'Beschrijving',
    keywords: 'Trefwoorden (gescheiden door komma\'s)',
    business: 'Bedrijfsnaam',
    city: 'Stad',
    district: 'District',
    country: 'Land',
    gpsTab: 'GPS Locatie',
    metaTab: 'Metadata',
    preview: 'Afbeeldingsmetadata',
    gpsFound: 'Status: Gevonden',
    gpsNotFound: 'Status: Niet gevonden',
    noGpsMsg: 'Geen GPS-coördinaten gevonden in deze afbeelding.',
    imgDetails: 'Details afbeelding',
    cameraInfo: 'Camera Info',
    format: 'Formaat',
    dimensions: 'Dimensies',
    make: 'Cameramerk',
    model: 'Cameramodel',
    date: 'Opnamedatum',
    writeSingle: 'EXIF bijwerken & Downloaden',
    editImage: 'Bewerken',
    processing: 'Verwerken...',
  },
  ar: {
    dropTitle: 'قم بإسقاط صور JPG أو JPEG هنا',
    dropSub: 'أو انقر لتحديد الملفات',
    batchApply: 'تطبيق على جميع الصور',
    clearAll: 'مسح الكل',
    searchPlaceholder: 'ابحث عن مدينة، عنوان...',
    lat: 'خط العرض',
    lng: 'خط الطول',
    invalidCoords: 'أدخل إحداثيات عشرية صالحة',
    writeTags: 'كتابة البيانات الوصفية والتحميل',
    downloading: 'جاري المعالجة...',
    successFiles: 'تمت معالجة الملفات بنجاح!',
    errorNoLoc: 'يرجى تحديد موقع على الخريطة قبل التطبيق.',
    errorGeneral: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    metadataHeader: 'بيانات SEO المحلية (اختياري)',
    title: 'العنوان',
    desc: 'الوصف',
    keywords: 'كلمات مفتاحية (مفصولة بفواصل)',
    business: 'اسم الشركة',
    city: 'المدينة',
    district: 'الحي',
    country: 'البلد',
    gpsTab: 'موقع GPS',
    metaTab: 'البيانات الوصفية',
    preview: 'تفاصيل الصورة',
    gpsFound: 'الحالة: تم العثور عليه',
    gpsNotFound: 'الحالة: غير موجود',
    noGpsMsg: 'لا توجد إحداثيات GPS في هذه الصورة.',
    imgDetails: 'تفاصيل الصورة',
    cameraInfo: 'معلومات الكاميرا',
    format: 'الصيغة',
    dimensions: 'الأبعاد',
    make: 'ماركة الكاميرا',
    model: 'موديل الكاميرا',
    date: 'تاريخ الالتقاط',
    writeSingle: 'تحديث EXIF والتحميل',
    editImage: 'تعديل',
    processing: 'جاري المعالجة...',
  },
  hi: {
    dropTitle: 'यहाँ JPG या JPEG चित्र छोड़ें',
    dropSub: 'या फ़ाइलें चुनने के लिए क्लिक करें',
    batchApply: 'सभी छवियों पर लागू करें',
    clearAll: 'सभी साफ़ करें',
    searchPlaceholder: 'शहर, पता खोजें...',
    lat: 'अक्षांश',
    lng: 'देशांतर',
    invalidCoords: 'वैध दशमलव निर्देशांक दर्ज करें',
    writeTags: 'मेटाडेटा लिखें और डाउनलोड करें',
    downloading: 'संसाधित किया जा रहा है...',
    successFiles: 'फ़ाइलें सफलतापूर्वक संसाधित की गईं!',
    errorNoLoc: 'कृपया जियोगटैग लागू करने से पहले मैप पर एक स्थान पिन करें।',
    errorGeneral: 'एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
    metadataHeader: 'स्थानीय एसईओ मेटाडेटा (वैकल्पिक)',
    title: 'शीर्षक',
    desc: 'विवरण',
    keywords: 'कीवर्ड (अल्पविराम से अलग करें)',
    business: 'व्यवसाय का नाम',
    city: 'शहर',
    district: 'जिला',
    country: 'देश',
    gpsTab: 'जीपीएस स्थान',
    metaTab: 'मेटाडेटा',
    preview: 'छवि मेटाडेटा',
    gpsFound: 'स्थिति: मिला',
    gpsNotFound: 'स्थिति: नहीं मिला',
    noGpsMsg: 'इस छवि में कोई जीपीएस निर्देशांक नहीं मिले।',
    imgDetails: 'छवि विवरण',
    cameraInfo: 'कैमरा जानकारी',
    format: 'प्रारूप',
    dimensions: 'आयाम',
    make: 'कैमरा मेक',
    model: 'कैमरा मॉडल',
    date: 'लेने की तिथि',
    writeSingle: 'EXIF अपडेट करें और डाउनलोड करें',
    editImage: 'संपादित करें',
    processing: 'संसाधित...',
  },
  id: {
    dropTitle: 'Seret gambar JPG atau JPEG ke sini',
    dropSub: 'atau klik untuk memilih file',
    batchApply: 'Terapkan ke Semua Gambar',
    clearAll: 'Hapus Semua',
    searchPlaceholder: 'Cari kota, alamat, landmark...',
    lat: 'Garis Lintang',
    lng: 'Garis Bujur',
    invalidCoords: 'Masukkan koordinat desimal yang valid',
    writeTags: 'Tulis Metadata & Unduh',
    downloading: 'Memproses...',
    successFiles: 'file berhasil diproses!',
    errorNoLoc: 'Harap pin lokasi di peta sebelum menerapkan geotag.',
    errorGeneral: 'Terjadi kesalahan. Silakan coba lagi.',
    metadataHeader: 'Metadata SEO Lokal (Opsional)',
    title: 'Judul',
    desc: 'Deskripsi',
    keywords: 'Kata Kunci (pisahkan dengan koma)',
    business: 'Nama Bisnis',
    city: 'Kota',
    district: 'Kecamatan',
    country: 'Negara',
    gpsTab: 'Lokasi GPS',
    metaTab: 'Metadata',
    preview: 'Metadata Gambar',
    gpsFound: 'Status: Ditemukan',
    gpsNotFound: 'Status: Tidak ditemukan',
    noGpsMsg: 'Tidak ada koordinat GPS yang ditemukan di gambar ini.',
    imgDetails: 'Detail Gambar',
    cameraInfo: 'Info Kamera',
    format: 'Format',
    dimensions: 'Dimensi',
    make: 'Merek Kamera',
    model: 'Model Kamera',
    date: 'Tanggal Diambil',
    writeSingle: 'Perbarui EXIF & Unduh',
    editImage: 'Edit',
    processing: 'Memproses...',
  },
  ja: {
    dropTitle: 'ここにJPG画像をドロップ',
    dropSub: 'またはクリックしてファイルを選択',
    batchApply: 'すべての画像に適用',
    clearAll: 'すべてクリア',
    searchPlaceholder: '都市、住所、ランドマークを検索...',
    lat: '緯度',
    lng: '経度',
    invalidCoords: '有効な10進座標を入力してください',
    writeTags: 'メタデータを書き込んでダウンロード',
    downloading: '処理中...',
    successFiles: 'ファイルの処理が完了しました！',
    errorNoLoc: 'ジオタグを適用する前にマップ上で場所をピン留めしてください。',
    errorGeneral: 'エラーが発生しました。もう一度お試しください。',
    metadataHeader: 'ローカルSEOメタデータ（任意）',
    title: 'タイトル',
    desc: '説明',
    keywords: 'キーワード（カンマ区切り）',
    business: 'ビジネス名',
    city: '都市',
    district: '地区',
    country: '国',
    gpsTab: 'GPS位置情報',
    metaTab: 'メタデータ',
    preview: '画像のメタデータ',
    gpsFound: '状態: 検出済み',
    gpsNotFound: '状態: 未検出',
    noGpsMsg: 'この画像にはGPS座標がありません。',
    imgDetails: '画像の詳細',
    cameraInfo: 'カメラ情報',
    format: 'フォーマット',
    dimensions: '寸法',
    make: 'カメラのブランド',
    model: 'カメラのモデル',
    date: '撮影日',
    writeSingle: 'EXIFを更新してダウンロード',
    editImage: '編集',
    processing: '処理中...',
  },
  ko: {
    dropTitle: '여기에 JPG/JPEG 이미지를 드롭하세요',
    dropSub: '또는 클릭하여 파일을 선택하세요',
    batchApply: '모든 이미지에 적용',
    clearAll: '모두 지우기',
    searchPlaceholder: '도시, 주소, 랜드마크 검색...',
    lat: '위도',
    lng: '경도',
    invalidCoords: '유효한 십진수 좌표를 입력하세요',
    writeTags: '메타데이터 쓰기 및 다운로드',
    downloading: '처리 중...',
    successFiles: '개 파일이 성공적으로 처리되었습니다!',
    errorNoLoc: '지오태그를 적용하기 전에 지도에 위치를 고정하세요.',
    errorGeneral: '오류가 발생했습니다. 다시 시도해 주세요.',
    metadataHeader: '로컬 SEO 메타데이터 (선택사항)',
    title: '제목',
    desc: '설명',
    keywords: '키워드 (쉼표로 구분)',
    business: '업체명',
    city: '도시',
    district: '지역',
    country: '국가',
    gpsTab: 'GPS 위치',
    metaTab: '메타데이터',
    preview: '이미지 메타데이터',
    gpsFound: '상태: 찾음',
    gpsNotFound: '상태: 찾을 수 없음',
    noGpsMsg: '이 이미지에서 GPS 좌표를 찾을 수 없습니다.',
    imgDetails: '이미지 세부 정보',
    cameraInfo: '카메라 정보',
    format: '형식',
    dimensions: '크기',
    make: '카메라 제조사',
    model: '카메라 모델',
    date: '촬영 날짜',
    writeSingle: 'EXIF 업데이트 및 다운로드',
    editImage: '편집',
    processing: '처리 중...',
  }
}
